# Generated by Django 4.2.20 on 2025-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0003_person_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
